### ISSUE TITLE
Parsing error loading recipe ruined_equipment:ruined_smithing_set_empower

### ISSUE THREAD

**Issue by Maelep** [Pepperoni-Jabroni/RuinedEquipment#7]
`[Worker-Main-10/ERROR]: Parsing error loading recipe ruined_equipment:ruined_smithing_set_empower
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'ruined_equipment:ruined_set_empower'
	at net.minecraft.class_1863.method_17875(class_1863.java:122) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_282]
	at net.minecraft.class_1863.method_17720(class_1863.java:122) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_282]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]`

`{ 
	// When 'true', Ruined items will be set in-hand when they break instead of going into the inventory.
	"enableSetRuinedItemInHand": false,
	// When 'true', repairing Ruined items using the Crafting Grid will be enabled.
	"enableCraftingGridRuinedRepair": true,
	// When 'true', repairing Ruined items using the Anvil will be enabled.
	"enableAnvilRuinedRepair": true,
	// When 'true', 'Empowering' a Ruined item using the Smithing Table will be enabled.
	"enableSmithingRuinedEmpowered": false,
	// The Item to be used for applying 'Empowered' to a Ruined item in a Smithing Table.
	"empowermentSmithingItem": "minecraft:netherite_scrap",
	// When 'true', the 'Ruined Equipment' Creative inventory tab will be displayed.
	"enableCreativeInventoryTab": true,
	// When 'true', Ruined items with Mending held in your hands will be repaired when you collect XP.
	"enableRuinedMendingRepair": false
}`

**Comment by Pepperoni-Jabroni** [comment]
Thank you for taking the time to file a bug report, u/Maelep! Can you provide me more information about your mod's config and your list of all installed mods?
